name: Demo Gold Image Pipeline for NGINX

on:
  push:
    branches:
      - main

jobs:
  gold-image: 
    name: Gold Image Pipeline
    runs-on: ubuntu-20.04
    env:
      CHEF_LICENSE: accept
      PROFILE: my_nginx
    steps:
      - name: Update ubuntu
        run: sudo apt-get update -y